name: Skip CI
on:
  push:
    branches:
      - main
      - release/**
    paths-ignore:
      - '.prettierignore'
      - 'CHANGELOG.md'
      - 'README.md'
      - '.github/CODEOWNERS'
      - '.github/pull_request_template.md'
      - '.github/ISSUE_TEMPLATE/BUG_REPORT.md'
      - '.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md'
     # trigger build
     # - '.github/workflows/**.yml' #for testing
  pull_request:
    paths-ignore:
      - '.prettierignore'
      - 'CHANGELOG.md'
      - 'README.md'
      - '.github/CODEOWNERS'
      - '.github/pull_request_template.md'
      - '.github/ISSUE_TEMPLATE/BUG_REPORT.md'
      - '.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md'
     # trigger build
     # - '.github/workflows/**.yml' #for testing

jobs:
  has_changes:
    runs-on: ubuntu-latest
    steps:
       -uses: actions/checkout@v2
